run_metadata:
  default_input_namespace: ryancorbyn
  default_output_namespace: ryancorbyn
  description: Run Image analysis script
  script: jupyter nbconvert --to html --execute Image_and_Script/simple_analysis.ipynb