run_metadata:
  default_input_namespace: David
  default_output_namespace: David
  description: Test_run_imagescript
  script: jupyter nbconvert --to html --execute Image_and_Script/Jupyter/simple_analysis.ipynb
  remote_repo: https://github.com/pharmlovex/FairDataPipepline

register:
- namespace: David
  full_name: David McGuinness
  website: https://github.com/dhmcg77

- external_object: jupyter_testing_image
  namespace_name: David
  root: https://github.com/pharmlovex/FairDataPipepline/raw/David/
  path: Image_and_Script/Jupyter_testing/single_frame_image.tif
  title: Static image
  description: Static image for analyse
  identifier: https://doi.org/10.1038/s41592-020-0856-2
  file_type: tif
  release_date: 2024-06-13T12:00
  version: "1.1.0"
  primary: "false"

write:
- data_product: jupyter_testing_analysis
  description: Excel data
  file_type: csv

- data_product: jupyter_testing_figure
  description: plot
  file_type: tif

- data_product: jupyter_html
  description: webpage
  file_type: html
