git:
  local_repo: /home/jovyan/work/FairDataPipepline
  remote: origin
  remote_repo: https://github.com/pharmlovex/FairDataPipepline.git
namespaces:
  input: realailaantoniou-kourounioti
  output: realailaantoniou-kourounioti
registries:
  origin:
    data_store: https://test-data.fairdatapipeline.org/data/
    token: /home/jovyan/.fair/cli/remotetoken.txt
    uri: https://test-data.fairdatapipeline.org/api/
user:
  email: rea.antkour@gmail.com
  family_name: Antoniou-Kourounioti
  given_names: Rea Laila
  name: Rea Laila Antoniou-Kourounioti
  orcid: 0000-0001-5226-521X
  remote_user: ReaAntKour
  uri: https://orcid.org/0000-0001-5226-521X
