run_metadata:
  default_input_namespace: pharmlovex
  default_output_namespace: pharmlovex
  description: Project description
  script: python ~/work/FairDataPipepline/Image_and_Script/image/image/main.py
  remote_repo: https://github.com/pharmlovex/FairDataPipepline

register:
- namespace: pharmlovex
  full_name: Ifedayo Ojo
  website: https://github.com/pharmlovex


read:
- data_product: image/data
  path: Image_and_Script/image/image/single_frame_image.tif
 

write:
- data_product: image/results/image_analysis
  description: Image Morphology results
  file_type: csv

- data_product: image/results/image_mask
  description: Image Mask
  file_type: tiff
